name: Run tests with tox
on: [push]
jobs:
  # install pip, tox
  tox:
    name: tox tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - testenv: py
            python: 3.8
          - testenv: py
            python: 3.9
          - testenv: mypy
            python: 3.8
          - testenv: flake8
            python: 3.8
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"
      - name: install tox
        run: pip install tox
      - run: "tox -e ${{ matrix.testenv}}"

# run weekly every sunday-evening pikepdf-main