name: Run tests with tox
on: [push]
jobs:
  # install pip, tox
  self-tests:
    name: pytest tests with tox
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: 3.8
            testenv: py
          - python: 3.9
            testenv: py            
    steps:
      - uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"
      - name: install tox
        run: pip install tox
      - name: install texlive-base
        run: sudo apt-get install --no-install-recommends texlive-latex-recommended 
      - name: check pdflatex installation
        run: pdflatex -version
      - name: install poppler-utils for textract
        run: sudo apt-get install poppler-utils
      - name: run tox
        run: "tox -e ${{ matrix.testenv}}"
  quality:
    name: quality tests with tox
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: 3.8
        testenv: [mypy, flake8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"
      - name: install tox
        run: pip install tox
      - name: run tox
        run: "tox -e ${{ matrix.testenv}}"


# run weekly every sunday-evening pikepdf-main