name: Run tests with tox
on: [push]
jobs:
  # install pip, tox
  pytest:
    name: tests with pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install tox
        run: pip install tox
      - run: tox -e py
  mypy:
    name: typing with mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install tox
        run: pip install tox
      - run: tox -e mypy
  flake8:
    name: linting with flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install tox
        run: pip install tox
      - run: tox -e flake8