name: Run tests with tox
on: [push]
jobs:
  self-tests:
    name: pytest tests with tox
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: "3.12"
            testenv: testing
          - python: "3.13"
            testenv: testing            
    steps:
      - uses: actions/checkout@v4
      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python }}"
      - name: install tox
        run: pip install tox
      - name: install texlive-base and poppler-utils
        run: sudo apt-get install --no-install-recommends texlive-latex-recommended poppler-utils
      - name: run tox
        run: "tox -e ${{ matrix.testenv}}"
  quality:
    name: quality tests with tox
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testenv: [typing, linting]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install tox
        run: pip install tox
      - name: run tox
        run: "tox -e ${{ matrix.testenv}}"