name: Run tests with tox
on: [push]
jobs:
  self-tests:
    name: pytest tests with tox
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: 3.8
            testenv: py
          - python: 3.9
            testenv: py            
    steps:
      - uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"
      - name: install tox
        run: pip install tox
      - name: install texlive-base and poppler-utils (textract)
        run: sudo apt-get install --no-install-recommends texlive-latex-recommended poppler-utils
      - name: run tox
        run: "tox -e ${{ matrix.testenv}}"
  quality:
    name: quality tests with tox
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testenv: [mypy, linting]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install tox
        run: pip install tox
      - name: run tox
        run: "tox -e ${{ matrix.testenv}}"


# TODO run weekly every sunday-evening pikepdf-main